a=str(input("Enter a str -"))
b=int(a)
print("value in interger is-",b)
c=float(a)
print("value in float is-",c)
d=bool(a)
print("value in boolian is -",d)
e=complex(a)
print("value in complex is-",e)
