a=float(input("Enter an float nub-"))
b=int(a)
print("value in interger is-",b)
c=str(a)
print("value in str is-",c)
d=bool(a)
print("value in boolian is -",d)
e=complex(a)
print("value in complex is-",e)
